#!/bin/bash

# Vai para a pasta raiz do projeto (uma acima da pasta do script)
cd "$(dirname "$0")/.."

VENV="./venv"

if [ ! -d "$VENV" ]; then
  echo "🔧 Criando ambiente virtual..."
  python3 -m venv venv
fi

source venv/bin/activate

echo "📦 Instalando dependências..."
pip install --break-system-packages -r requirements.txt

echo "🚀 Iniciando servidor Flask..."
python main.py
